openapi: 3.0.1
info:
  title: Quick Quote API
  description: This API captures two interactions. The first is the quote response the broker sees from Greenscreens, and the second is the quote response the broker is sending to the customer.
  version: "1.0"
paths:
  /gs-quote:
    post:
      summary: Receive GS Quote Response
      requestBody:
        description: A Greenscreens Quote Response object with user and customer details
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GSQuoteRequest"
      responses:
        "200":
          description: Successfully received GS quote response
  /trident-quote:
    post:
      summary: Receive Trident Quote Response
      requestBody:
        description: A Quote Response object from the broker after creating an email reply draft to send to the customer
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TridentQuoteRequest"
      responses:
        "200":
          description: Successful request
components:
  schemas:
    GSQuoteRequest:
      type: object
      properties:
        id:
          type: string
        userEmail:
          type: string
        customerEmail:
          type: string
        stops:
          type: array
          items:
            $ref: "#/components/schemas/Stop"
        selectedRateName:
          $ref: "#/components/schemas/SelectedCarrierType"
        networkLaneRateDistance:
          type: number
        networkLaneRateTargetBuy:
          type: number
        networkLaneRateConfidenceLevel:
          type: number
        laneRateDistance:
          type: number
        laneRateTargetBuy:
          type: number
        laneRateConfidenceLevel:
          type: number
      required:
        - userEmail
        - customerEmail
        - stops
        - selectedRateName
        - networkLaneRateDistance
        - networkLaneRateTargetBuy
        - networkLaneRateConfidenceLevel
        - laneRateDistance
        - laneRateTargetBuy
        - laneRateConfidenceLevel
    TridentQuoteRequest:
      type: object
      properties:
        gsQuoteId:
          type: string
        userEmail:
          type: string
        customerEmail:
          type: string
        stops:
          type: array
          items:
            $ref: "#/components/schemas/Stop"
        carrierCost:
          type: number
        margin:
          type: number
        targetSell:
          type: number
        draftResponse:
          type: string
      required:
        - userEmail
        - customerEmail
        - stops
        - carrierCost
        - margin
        - targetSell
        - draftResponse
    Stop:
      type: object
      properties:
        order:
          type: integer
        city:
          type: string
        state:
          type: string
        zip:
          type: string
        country:
          type: string
      required:
        - order
        - city
        - state
        - zip
        - country
    SelectedCarrierType:
      type: string
      enum:
        - NETWORK
        - BUYPOWER
